export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const EMPTY_CART = 'EMTPY_CART';
export const SAVE_CART_PAYMENT_METHOD = 'SAVE_CART_PAYMENT_METHOD';
export const SAVE_CART_SHIPPING_ADDRESS = 'SAVE_CART_SHIPPING_ADDRESS';