export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";
export const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL";

export const PAY_ORDER_REQUEST = "PAY_ORDER_REQUEST";
export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCESS";
export const PAY_ORDER_FAIL = "PAY_ORDER_FAIL";
export const PAY_ORDER_CLEAR = "PAY_ORDER_CLEAR";

export const MY_ORDER_LIST_REQUEST = "MY_ORDER_LIST_REQUEST";
export const MY_ORDER_LIST_SUCCESS = "MY_ORDER_LIST_SUCCESS";
export const MY_ORDER_LIST_FAIL = "MY_ORDER_LIST_FAIL";
export const MY_ORDER_LIST_RESET = "MY_ORDER_LIST_RESET";

export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
export const ALL_ORDERS_FAIL = "ALL_ORDERS_FAIL";

export const DELIVER_ORDER_REQUEST = " DELIVER_ORDER_REQUEST";
export const DELIVER_ORDER_SUCCESS = " DELIVER_ORDER_SUCCESS";
export const DELIVER_ORDER_FAIL = " DELIVER_ORDER_FAIL";
export const DELIVER_ORDER_CLEAR = " DELIVER_ORDER_CLEAR";
