export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";
export const PRODUCT_DETAILL_CLEAR = "PRODUCT_DETAIL_CLEAR";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const CREATE_PRODUCT_CLEAR = "CREATE_PRODUCT_CLEAR";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_CLEAR = "UPDATE_PRODUCT_CLEAR";

export const CREATE_PRODUCT_REVIEW_REQUEST = " CREATE_PRODUCT_REVIEW_REQUEST";
export const CREATE_PRODUCT_REVIEW_SUCCESS = " CREATE_PRODUCT_REVIEW_SUCCESS";
export const CREATE_PRODUCT_REVIEW_FAIL = "CREATE_PRODUCT_REVIEW_FAIL";
export const CREATE_PRODUCT_REVIEW_CLEAR = "CREATE_PRODUCT_REVIEW_CLEAR";

export const TOP_PRODUCT_REQUEST = "TOP_PRODUCT_REQUEST"
export const TOP_PRODUCT_SUCCESS = "TOP_PRODUCT_SUCCESS"
export const TOP_PRODUCT_FAIL= "TOP_PRODUCT_FAIL"

export const ADMIN_PRODUCTS_REQUEST = "ADMIN_PRODUCTS_REQUEST";
export const ADMIN_PRODUCTS_SUCCESS = "ADMIN_PRODUCTS_SUCCESS";
export const ADMIN_PRODUCTS_FAIL = "ADMIN_PRODUCTS_FAIL";
